# -*- coding: utf-8 -*-
"""Exploratory Data Analysis - Terrorism.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8JUgaW9lIdyFK-lC0_LAUDHxznX-98x

Coderscave
Exploratory Data Analysis - Terrorism
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv('/content/globalterrorismdb_0718dist.csv', encoding='ISO-8859-1')

print(data.info())

print(data.head())

"""Exploratory Data Analysis

Example 1: Number of terrorist attacks per year
"""

attacks_per_year = data.groupby('iyear').size()
plt.figure(figsize=(10, 6))
sns.lineplot(x=attacks_per_year.index, y=attacks_per_year.values)
plt.title('Number of Terrorist Attacks per Year')
plt.xlabel('Year')
plt.ylabel('Number of Attacks')
plt.show()

"""Example 2: Types of attacks"""

attack_types = data['attacktype1_txt'].value_counts()
plt.figure(figsize=(10, 6))
sns.barplot(x=attack_types.index, y=attack_types.values)
plt.title('Types of Attacks')
plt.xlabel('Attack Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Example 3: Most affected regions"""

top_regions = data['region_txt'].value_counts().nlargest(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=top_regions.index, y=top_regions.values)
plt.title('Top 10 Most Affected Regions')
plt.xlabel('Region')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Example 4: Correlation between variables"""

correlation_matrix = data.corr()
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True,cmap='hot')
plt.title('Correlation Matrix')
plt.show()

"""Example 5: Target types"""

target_types = data['targtype1_txt'].value_counts()
plt.figure(figsize=(10, 6))
sns.barplot(x=target_types.index, y=target_types.values)
plt.title('Types of Targets')
plt.xlabel('Target Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Example 6: Weapon types"""

weapon_types = data['weaptype1_txt'].value_counts()
plt.figure(figsize=(10, 6))
sns.barplot(x=weapon_types.index, y=weapon_types.values)
plt.title('Types of Weapons Used')
plt.xlabel('Weapon Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Example 7: Most active terrorist groups"""

active_groups = data['gname'].value_counts().nlargest(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=active_groups.index, y=active_groups.values)
plt.title('Top 10 Most Active Terrorist Groups')
plt.xlabel('Terrorist Group')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()